# Generated by Django 3.1.4 on 2020-12-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('ts', models.CharField(max_length=50)),
                ('lat_long', models.CharField(max_length=100)),
                ('noun', models.CharField(max_length=10)),
                ('verb', models.CharField(max_length=10)),
                ('time_spent_on_the_screen', models.IntegerField()),
                ('properties', models.JSONField()),
            ],
        ),
    ]
